import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anime App",
  description: "Generated by Moatsem Osama",
  metadataBase: new URL("https://anime-website-app.netlify.app/"), // ضع هنا الدومين الفعلي
   icons: {
    icon: "/favicon.png",
  },
  openGraph: {
    title: "Anime App",
    description: "Anime website with ratings and details",
    url: "https://anime-website-app.netlify.app/",
    siteName: "AnimeSite",
    images: ["/bg.png"],
    locale: "ar_EG",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Anime App",
    description: "Anime website with ratings and details",
    creator: "Moatsem Osama",
    images: ["/bg.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#1a1f1b] antialiased`}
      >
        <Header/>
        <main >
        {children}
        </main>
      </body>
    </html>
  );
}
